language: node_js

sudo: false

node_js:
  - "8"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

script:
  - cp _config.prod.yml _config.yml
  - npm run build

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master